#!/bin/env ruby

require "pty"
require "io/console"

r, w = IO.pipe

STDERR.reopen w
w.close


ChildWrapperPID = $$


fork do
    begin
        loop do
            IO.select [r]
            buff = r.readpartial(4096)
            File.open "/tmp/test.zsh.log", "a" do |f|
                f.write "#{Time.now.strftime("%H:%M:%S.%L")}(wrapper)[#{ChildWrapperPID}] #{buff}"
            end
        end
    rescue => e
        File.open "/tmp/test.zsh.log", "a" do |f|
            f.write "#{Time.now.strftime("%H:%M:%S.%L")}(logger)[$$] ERROR: #{e.message}\n"
        end
    end
end


tty_in  = IO.for_fd(Integer(ENV.fetch("TTY_IN_FD")))
wsz = tty_in.winsize

tty_out = IO.for_fd(Integer(ENV.fetch("TTY_OUT_FD")), "w")
master, slave = PTY.open
master.winsize = wsz



trap :WINCH do
    STDERR.puts "Received WINCH signal to #{$$}"
    begin
        new_wsz = tty_in.winsize
        if new_wsz != wsz
            wsz = new_wsz
            if master && !master.closed?
                master.winsize = wsz
            end
        end
    rescue => e
        STDERR.puts "trap WINCH error #{$$}, ERROR: #{e.message}"
    end
end

IO.write(ARGV[0], "#{$$} #{slave.path}\n")
slave.close
orig = tty_in.raw!(intr: true)
trap("TERM"){ exit 0 }
trap :INT do 
    STDERR.puts "Received INT signal to #{$$}"
    master.write "\x03" # Ctrl-C
end
trap :TSTP do
    STDERR.puts "Received TSTP signal to #{$$}"
    master.write "\x1A" # Ctrl-Z
end
trap :QUIT do
    STDERR.puts "Received QUIT signal to #{$$}"
    master.write "\x1C" # Ctrl-\
end


class Subst
    attr_reader :file, :time
    def initialize file
        @file = file
        @time = Time.now
        @@filters ||= {}
        @@filters[file] = self
    end
    def self.gsub! str, left
        @@filters ||= {}
        str.insert 0, left
        left.clear
        @@filters.values.sort_by{ |filter| filter.time }.reverse_each do |filter|
            filter.gsub str, left
        end
    end
end


class RbSubst
    def initialize file, filter
        super file
        @filter = filter
        instance_eval filter
    end
end


def registerFilter file
    filter = IO.read(file).strip
    begin
        STDERR.puts "Registering filter: #{filter.inspect} from file: #{file}"
        if file =~ /\.rb$/
            RbSubst.new file, filter
            return
        end
    rescue ArgumentError => e
        STDERR.puts "Error registering filter from file #{file}: #{e.message}"
    rescue RegexpError => e
        STDERR.puts "Invalid regex in filter from file #{file}: #{e.message}"
    end
end


trap :USR1 do
    STDERR.puts "Received USR1 signal to #{$$}"
    addFilter
end

def split_valid_utf8_and_tail_with_colored_invalid(buf)
    bytes = buf.b.bytes
    out = +""
    i = 0

    while i < bytes.length
        b0 = bytes[i]

        if b0 <= 0x7F
            out << b0
            i += 1
            next
        end

        expected_len = case b0
                       when 0xC2..0xDF
                           2
                       when 0xE0..0xEF
                           3
                       when 0xF0..0xF4
                           4
                       else
                           nil
                       end

        if expected_len.nil?
            out << format("\e[32;45m\\x%02x\e[0m", b0)
            i += 1
            next
        end

        remain = bytes.length - i
        if remain < expected_len
            tail = bytes[i, remain].pack("C*").b
            return [out.force_encoding(Encoding::UTF_8), tail]
        end

        seq = bytes[i, expected_len]
        unless seq[1..].all? { |b| (b & 0xC0) == 0x80 }
            out << format("\e[32;45m\\x%02x\e[0m", b0)
            i += 1
            next
        end

        ch = seq.pack("C*").force_encoding(Encoding::UTF_8)
        if ch.valid_encoding?
            out << ch
            i += expected_len
        else
            out << format("\e[32;45m\\x%02x\e[0m", b0)
            i += 1
        end
    end

    [out.force_encoding(Encoding::UTF_8), "".b]
end


STDERR.puts "Child process started with PID #{Process.pid}"
start_time = Time.now
begin
    uLeft = ""
    mLeft = "".b
    buff = "".b
    readers = [tty_in, master]
    loop do
        rs, = IO.select(readers, nil, nil)
        if rs.include?(tty_in)
            begin
                tty_in.readpartial(4096, buff)
            rescue EOFError
                readers.delete(tty_in)
                next
            end
            master.write buff
        end
        if rs.include?(master)
            begin
                master.readpartial(4096, buff)
            rescue EOFError
                readers.delete(master)
                next
            end
            d, mLeft = split_valid_utf8_and_tail_with_colored_invalid(mLeft + buff.b)
            # 加工ポイント
            d = d.gsub("ERROR", "\e[31mERROR\e[0m")
            STDERR.write(d.inspect + "\n")
            if Subst.gsub! d, uLeft
                STDERR.write("Substitution applied: " + d.inspect + "\n")
            end
            STDERR.flush
            tty_out.write(d)
            tty_out.flush
        end
    end
rescue Errno::EIO
# slave 側が閉じた時の通常終了
    if Time.now - start_time < 10
        sleep 0.1
        retry
    end
ensure
    STDERR.puts "Child process exited (#{Process.pid})"
    tty_in.cooked! rescue nil
    master.close rescue nil
end

